### ISSUE TITLE
Autocomplete is very slow

### ISSUE THREAD

**Issue by ahasall** [FabioAntunes/fish-nvm#38]
Hi,

Autocompletion works on Fish 3 but is very slow.

Checkout this [asciinema](https://asciinema.org/a/QwEpU8gQFme7e4ZaGcywAdD16) showing the issue

Thank you

**Comment by FabioAntunes** [comment]
Hey @ahasall is that only on the first run? If you open a new session. try to do autocomplete, it will be slow. try to do it again. Will it be faster?

The first run will always be slower, due to the sourcing of nvm on the fly. After the first sourcing, you should have a normal speed.

**Comment by ahasall** [comment]
It happens all the time not only at startup.

**Comment by c10b10** [comment]
I can confirm this happens to me as well.
