### ISSUE TITLE
Update Docs

### ISSUE THREAD

**Issue by eh-am** [FabioAntunes/fish-nvm#39]
Currently there's a section suggesting `fnm`:
>Check out also fnm a pure fish node version manager with automatic version switching.

But in reality `fnm` doesn't support that anymore, so it should be removed
https://github.com/jorgebucaran/fish-nvm/issues/58#issuecomment-452573419

**Comment by FabioAntunes** [comment]
Feel free to create a PR

**Comment by eh-am** [comment]
sure, do you wanna keep the section or remove it entirely?
