### ISSUE TITLE
Node prints all output first when quitting the program

### ISSUE THREAD

**Issue by alx365** [FabioAntunes/fish-nvm#48]
I'm not sure if its an issue with this application, but i don't know where else to start.

As i already said in the title, (not all) node and npm commands that are not quitting automatically because they are finished executing, are first logging their stuff when i quit the application with ctrl+c.
I can't reproduce the behavior with bash.  

If this is the wrong place to post this, maybe you could guide me to a better place to post this.

Thanks!

**Comment by FabioAntunes** [comment]
@alx365 apologies for the lack of response didn't get notified of this. Could you give me one example of one command that has this behaviour so I can try and reproduce this locally? Thanks and once again apologies for the 2 month delay

**Comment by alx365** [comment]
np, umm, i think the issue has resolved itself. at least i am not anymore experiencing it. I have no idea what i changed.
