### ISSUE TITLE
Auto nvm use when detecting .nvmrc ?

### ISSUE THREAD

**Issue by kiuKisas** [FabioAntunes/fish-nvm#58]
Hello, thank's for your plugin, really appreciate it. I was wondering if an easy way exist to automaticly call `nvm use` when I'm in my project folder with an `.nvmrc` file describing the current version of node needed for this project ? 
Thank's :)

**Comment by FabioAntunes** [comment]
Hey, @kiuKisas.

Not sure if I understood your question correctly. Do you want to call `nvm use` as soon as you enter a folder that has a `.nvmrc`? Is that it?

**Comment by kiuKisas** [comment]
Yeap, that's what I mean, sorry if I have not been clar

**Comment by FabioAntunes** [comment]
I can only think of two ways. Using a post_exec command on your config.fish

```
function postexec --on-event fish_postexec
    #check that the command we just run is a any sort of cd command
    if string match -q -- "*cd *" $argv;
      # check if the current folder has a .nvmrc if so run nvm use

  end
end
```

The other option could be messing around with your https://fishshell.com/docs/current/tutorial.html#prompt

```
function fish_prompt
    # check if the current folder has a .nvmrc if so run nvm use
end
```
