### ISSUE TITLE
does not fix "NVM not found" error when creating a new tmux pane

### ISSUE THREAD

**Issue by EdmundsEcho** [FabioAntunes/fish-nvm#65]
Hello -- Thank you for the plugin.  

I'm using a Mac M1 with alacritty and tmux.

It seems to work fine when I open a new terminal.  It also seems to work fine when I start a new tmux session.  However, when I create a new pane or window within tmux, I get the "NVM not found" error after it complains:

```fish
env: node: No such file or directory
```

Is this something you have encountered? Is something I can do to point tmux to the right place?

**Comment by FabioAntunes** [comment]
I don't use tmux so I'm not able to reproduce this.

When you you open a new pane or window within tmux what gives you that error? Running `node` command by itself?

Are you sure on your new window or pane you are using fish shell?

**Comment by EdmundsEcho** [comment]
Thank you for your response.

In my `tmux.conf` file I "commented-out" the following to fix the error.  I'm still not precisely clear what is calling `node` prior to my path being available.  In other words, it *should* be ok to use these settings...

`tmux.conf`
```
# shell
# set -g default-command /opt/homebrew/bin/fish
# set -g default-shell /opt/homebrew/bin/fish
``` 

I also use `alacritty` as my terminal emulator.  To fire-up `fish` with every new terminal session, I have chosen to set the `shell` property there.

alacritty.yml
```
shell:
  program: /opt/homebrew/bin/fish
```

This prevents the reported error. I'll close the issue.
