### ISSUE TITLE
Suppress `nvm_alias_command` prints

### ISSUE THREAD

**Issue by titolins** [FabioAntunes/fish-nvm#66]
Hey there, first of all thanks for the great plugin 😄 

This is a minor issue, but it is a bit annoying given it happens on every new prompt.

I'm using nvim, so I've added the `nvm_alias_command` to my `config.fish` file to have the binaries linked to my PATH.

And this is working great, with one caveat. Once the executables are created, all subsequent terminals I open have this `Ignored: ... (already exists)` prints. Is there a way to suppress those?

Tks!

EDIT: Adding a screenshot for reference
![Screenshot 2024-02-06 at 13 09 12](https://github.com/FabioAntunes/fish-nvm/assets/8942194/ca7cf69e-eea2-47f3-96b8-487d484baec2)

**Comment by titolins** [comment]
I realised I could just redirect stdout to achieve that: `nvm_alias_command > /dev/null`
Tks anyways 👍

**Comment by FabioAntunes** [comment]
Hey @ttlins glad that you found a solution, but in theory you should not have this in your config.fish.  You only run once and that's it.

**Comment by titolins** [comment]
Ah, that makes sense 😅 
Obrigado 🙏
